### ISSUE TITLE
Make volume creation more robust

### ISSUE THREAD

**Issue by waveywaves** [redhat-developer/jenkins-operator#22]
Wrong log during creation of PVC for Jenkins when persistentspec is given
https://github.com/redhat-developer/jenkins-operator/blob/main/controllers/jenkins_controller.go#L362

Cannot supply storageClassName for volume creation which would be later used by backup container. Create backups based on JenkinsRef and not ConfigRef. BackupConfig needs to be provided to the Jenkins instance and not the other way around.

BackupConfig should also be used to create scheduled backups.

**Comment by rosscdh** [comment]
seems important :)

**Comment by waveywaves** [comment]
Volume creation is more robus now with default storage class being used if not given and backupVolume+backupStrategy support instead of the earlier backupConfig support
