### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by rosscdh** [redhat-developer/jenkins-operator#30]
Hi there,

    firstly thanks for the decent looking operator, I am hoping to ask for a status of this repo?

Now that RH has taken over will maintenance be ongoing and expanded on?

**Comment by waveywaves** [comment]
@rosscdh Thank you for showing interest in this operator. Yes, we are maintaning and updating the repo to have a more robust operator which can be used in production.

**Comment by rosscdh** [comment]
Hi there @waveywaves thanks for the response.

May I ask what the roadmap looks like and what the expected first "official release" is, or is it usable now?

Also may I ask what the main instabilities in the previous iteration were?

Thanks and keep up the good work!

**Comment by waveywaves** [comment]
Thank you for your interest in the project. We will put out a roadmap soon regarding the usage of the operator and what lies ahead.
